name: dreamgaussian_test
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.2.2
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.10.14
  - pytorch=2.1.2
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - typing_extensions=4.9.0
  - gxx_linux-64=11.4.0
  - glm
  - libglvnd-egl-cos7-x86_64
  - cccl
  - pip:
    - open3d==0.18.0
    - mediapy==1.1.2
    - numpy==1.26.4
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - plyfile
    - opencv-python
